#gitlab:
#  image: 'gitlab/gitlab-ce:latest'
#  restart: always
#  hostname: 'gitlab.com'
#  environment:
#    GITLAB_OMNIBUS_CONFIG: |
#      external_url 'https://gitlab.com'
#      # Add any other gitlab.rb configuration here, each on its own line
#  ports:
#    - '8880:8880'
#    - '8433:8433'
#    - '8822:8822'
#  volumes:
#    - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\config:/etc/gitlab'
#    - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\logs:/var/log/gitlab'
#    - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\data:/var/opt/gitlab'


web:
  image: 'gitlab/gitlab-ce:latest'
  privileged: true
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
      # Add any other gitlab.rb configuration here, each on its own line
#  ports:
#    - '80:80'
#    - '443:443'
#    - '22:22'
#  volumes:
#    - '/srv/gitlab/config:/etc/gitlab'
#    - '/srv/gitlab/logs:/var/log/gitlab'
#    - '/srv/gitlab/data:/var/opt/gitlab'
  ports:
    - '8880:8880'
    - '8443:8443'
    - '8822:8822'
  volumes:
    - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\config:/etc/gitlab'
    - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\logs:/var/log/gitlab'
    - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\data:/var/opt/gitlab'