version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - '8880:8880'
      - '8433:8433'
      - '8822:8822'
    volumes:
      - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\config:/etc/gitlab'
      - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\logs:/var/log/gitlab'
      - 'D:\phpstudy\PHPTutorial\WWW\Code\docker\docker\gitlab\data:/var/opt/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    secrets:
      - gitlab_root_password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 4
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt